name: Generate Datas

on:
  workflow_dispatch:  # Permite executar o workflow manualmente

jobs:
  update_datas:
    runs-on: ubuntu-latest  # Ambiente onde o job será executado
    steps:
      - name: Check out code
        uses: actions/checkout@v2  # Faz checkout do código do repositório

      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: 'Merilyn2001'  # Seu nome de usuário do GitHub
          svg_out_path: 'dist/github-contribution-grid-snake.svg'  # Caminho onde o SVG será salvo
          gif_out_path: 'dist/github-contribution-grid-snake.gif'  # Se você também quiser gerar um GIF
          
